/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface GetAllRentPaymentRecordsResponse {
    meta: PropifyApi.Metadata;
    results: PropifyApi.RentPaymentRecord[];
}
