/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface RentPaymentHistory {
    /** The unique identifier for the applicant */
    id: string;
    /** The date record first entered propify */
    createdAt: string;
    /** The date record was last updated in propify */
    updatedAt: string;
    /** The external ID from the source vendor */
    xId: string;
    /** The external ID of the lease from the source vendor */
    xLeaseId?: string;
    /** The external ID of the resident from the source vendor */
    xResidentId?: string;
    /** The external ID of the property from the source vendor */
    xPropertyId?: string;
    /** The amount of the payment in cents */
    amountInCents?: number;
    /** The date the payment was received */
    dateReceived?: string;
    /** The type of payment */
    paymentType?: string;
    /** The status of the payment */
    paymentStatus?: string;
    /** The property management system of record */
    integrationVendor: PropifyApi.IntegrationVendor;
}
