/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllUnits: core.serialization.ObjectSchema<serializers.AllUnits.Raw, PropifyApi.AllUnits> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Unit)),
    });

export declare namespace AllUnits {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.Unit.Raw[];
    }
}
