/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllUnitsResponse: core.serialization.ObjectSchema<
    serializers.GetAllUnitsResponse.Raw,
    PropifyApi.GetAllUnitsResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Unit)),
});

export declare namespace GetAllUnitsResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: serializers.Unit.Raw[];
    }
}
