/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.unitPricing.getAllUnitPrices.Response.Raw,
    PropifyApi.GetAllUnitPricesResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetAllUnitPricesResponse);

export declare namespace Response {
    type Raw = serializers.GetAllUnitPricesResponse.Raw;
}
