/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.unitPricing.getAllUnitPricing.Response.Raw,
    PropifyApi.AllUnitPricing
> = core.serialization.lazyObject(async () => (await import("../../..")).AllUnitPricing);

export declare namespace Response {
    type Raw = serializers.AllUnitPricing.Raw;
}
