/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllVendors: core.serialization.ObjectSchema<serializers.AllVendors.Raw, PropifyApi.AllVendors> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Vendor)),
    });

export declare namespace AllVendors {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: (serializers.Vendor.Raw | undefined)[];
    }
}
