/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllVendorsResponse: core.serialization.ObjectSchema<
    serializers.GetAllVendorsResponse.Raw,
    PropifyApi.GetAllVendorsResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Vendor)),
});

export declare namespace GetAllVendorsResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: (serializers.Vendor.Raw | undefined)[];
    }
}
