/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Vendor: core.serialization.Schema<serializers.Vendor.Raw, PropifyApi.Vendor> =
    core.serialization.unknown();

export declare namespace Vendor {
    type Raw = unknown;
}
