/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export class DefaultError extends Error {
    readonly body: PropifyApi.DefaultErrorType;

    constructor(body: PropifyApi.DefaultErrorType) {
        super();
        Object.setPrototypeOf(this, DefaultError.prototype);
        this.body = body;
    }
}
