/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.rentPaymentHistory.getAllRecords.Response.Raw,
    PropifyApi.GetAllRentPaymentRecordsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetAllRentPaymentRecordsResponse);

export declare namespace Response {
    type Raw = serializers.GetAllRentPaymentRecordsResponse.Raw;
}
