/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.rentPaymentHistory.getAllRentPaymentHistory.Response.Raw,
    PropifyApi.AllRentPaymentHistory
> = core.serialization.lazyObject(async () => (await import("../../..")).AllRentPaymentHistory);

export declare namespace Response {
    type Raw = serializers.AllRentPaymentHistory.Raw;
}
