/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllUnitPricing: core.serialization.ObjectSchema<
    serializers.AllUnitPricing.Raw,
    PropifyApi.AllUnitPricing
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).UnitPricing)),
});

export declare namespace AllUnitPricing {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: (serializers.UnitPricing.Raw | undefined)[];
    }
}
