/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllUnitPricesResponse: core.serialization.ObjectSchema<
    serializers.GetAllUnitPricesResponse.Raw,
    PropifyApi.GetAllUnitPricesResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).UnitPrice)),
});

export declare namespace GetAllUnitPricesResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: (serializers.UnitPrice.Raw | undefined)[];
    }
}
