/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const UnitPrice: core.serialization.Schema<serializers.UnitPrice.Raw, PropifyApi.UnitPrice> =
    core.serialization.unknown();

export declare namespace UnitPrice {
    type Raw = unknown;
}
