/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const UnitPricing: core.serialization.Schema<serializers.UnitPricing.Raw, PropifyApi.UnitPricing> =
    core.serialization.unknown();

export declare namespace UnitPricing {
    type Raw = unknown;
}
