/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.vendors.getAllVendors.Response.Raw,
    PropifyApi.AllVendors
> = core.serialization.lazyObject(async () => (await import("../../..")).AllVendors);

export declare namespace Response {
    type Raw = serializers.AllVendors.Raw;
}
