/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class PropifyApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PropifyApiTimeoutError.prototype);
    }
}
