/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllListings: core.serialization.ObjectSchema<serializers.AllListings.Raw, PropifyApi.AllListings> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Listing)),
    });

export declare namespace AllListings {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: (serializers.Listing.Raw | undefined)[];
    }
}
