/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Listing: core.serialization.Schema<serializers.Listing.Raw, PropifyApi.Listing> =
    core.serialization.unknown();

export declare namespace Listing {
    type Raw = unknown;
}
