/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface GetAllVendorsResponse {
    meta: PropifyApi.Metadata;
    results: (PropifyApi.Vendor | undefined)[];
}
