/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllApplicants: core.serialization.ObjectSchema<serializers.AllApplicants.Raw, PropifyApi.AllApplicants> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).Applicant)
        ),
    });

export declare namespace AllApplicants {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.Applicant.Raw[];
    }
}
