/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllLeads: core.serialization.ObjectSchema<serializers.AllLeads.Raw, PropifyApi.AllLeads> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Lead)),
    });

export declare namespace AllLeads {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: (serializers.Lead.Raw | undefined)[];
    }
}
