/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllLeadsResponse: core.serialization.ObjectSchema<
    serializers.GetAllLeadsResponse.Raw,
    PropifyApi.GetAllLeadsResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Lead)),
});

export declare namespace GetAllLeadsResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: (serializers.Lead.Raw | undefined)[];
    }
}
