/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Lead: core.serialization.Schema<serializers.Lead.Raw, PropifyApi.Lead> = core.serialization.unknown();

export declare namespace Lead {
    type Raw = unknown;
}
