/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllResidents: core.serialization.ObjectSchema<serializers.AllResidents.Raw, PropifyApi.AllResidents> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).Resident)
        ),
    });

export declare namespace AllResidents {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.Resident.Raw[];
    }
}
