/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetResidentResponse: core.serialization.ObjectSchema<
    serializers.GetResidentResponse.Raw,
    PropifyApi.GetResidentResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.lazyObject(async () => (await import("../../..")).Resident).optional(),
});

export declare namespace GetResidentResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results?: serializers.Resident.Raw | null;
    }
}
