/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const SingleResident: core.serialization.ObjectSchema<
    serializers.SingleResident.Raw,
    PropifyApi.SingleResident
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
    results: core.serialization.lazyObject(async () => (await import("../../..")).Resident).optional(),
});

export declare namespace SingleResident {
    interface Raw {
        meta: serializers.Meta.Raw;
        results?: serializers.Resident.Raw | null;
    }
}
