/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllProperties: core.serialization.ObjectSchema<serializers.AllProperties.Raw, PropifyApi.AllProperties> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).Property)
        ),
    });

export declare namespace AllProperties {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.Property.Raw[];
    }
}
