/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllPropertiesResponse: core.serialization.ObjectSchema<
    serializers.GetAllPropertiesResponse.Raw,
    PropifyApi.GetAllPropertiesResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Property)),
});

export declare namespace GetAllPropertiesResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: serializers.Property.Raw[];
    }
}
