/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.leads.get.Response.Raw, PropifyApi.AllLeads> =
    core.serialization.lazyObject(async () => (await import("../../..")).AllLeads);

export declare namespace Response {
    type Raw = serializers.AllLeads.Raw;
}
