/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.leads.getAll.Response.Raw,
    PropifyApi.GetAllLeadsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetAllLeadsResponse);

export declare namespace Response {
    type Raw = serializers.GetAllLeadsResponse.Raw;
}
