/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface AllUnits {
    meta: PropifyApi.Meta;
    results: PropifyApi.Unit[];
}
