/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface Unit {
    /** The unique identifier for the property */
    id: string;
    /** The date record first entered propify */
    createdAt: string;
    /** The date record was last updated in propify */
    updatedAt: string;
    /** The external ID from the source vendor */
    xId: string;
    /** The external ID of the property from the source vendor */
    xPropertyId: string;
    /** The unit number */
    number?: string;
    /** The number of bedrooms */
    bedrooms?: string;
    /** The number of bathrooms */
    bathrooms?: string;
    /** The square footage of the unit */
    squareFeet?: number;
    /** The building number */
    buildingNumber?: string;
    /** The building name */
    buildingName?: string;
    /** The floor plan code */
    floorPlanCode?: string;
    /** The floor plan name */
    floorPlanName?: string;
    /** The street address line 1 */
    streetAddress1?: string;
    /** The street address line 2 */
    streetAddress2?: string;
    /** The city */
    city?: string;
    /** The state */
    state?: string;
    /** The zip code */
    zip?: string;
    /** The market rent amount in cents */
    rentAmountMarketInCents?: number;
    /** The minimum rent amount in cents */
    rentAmountMinInCents?: number;
    /** The maximum rent amount in cents */
    rentAmountMaxInCents?: number;
    /** Whether the unit is available */
    isAvailable?: boolean;
    /** Whether the unit is furnished */
    isFurnished?: boolean;
    /** Whether the unit is listed */
    isListed?: boolean;
    /** Whether the unit is vacant */
    isVacant?: boolean;
    /** The property management system of record */
    integrationVendor: PropifyApi.IntegrationVendor;
}
