/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface GetAllAccountingRecordsResponse {
    meta: PropifyApi.Metadata;
    results: (PropifyApi.AccountingRecord | undefined)[];
}
