/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.applicants.get.Response.Raw, PropifyApi.Applicant> =
    core.serialization.lazyObject(async () => (await import("../../..")).Applicant);

export declare namespace Response {
    type Raw = serializers.Applicant.Raw;
}
