/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AccountingRecord: core.serialization.Schema<
    serializers.AccountingRecord.Raw,
    PropifyApi.AccountingRecord
> = core.serialization.unknown();

export declare namespace AccountingRecord {
    type Raw = unknown;
}
