/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllAccountingRecords: core.serialization.ObjectSchema<
    serializers.AllAccountingRecords.Raw,
    PropifyApi.AllAccountingRecords
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).AccountingRecord)),
});

export declare namespace AllAccountingRecords {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: (serializers.AccountingRecord.Raw | undefined)[];
    }
}
