/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllAccountingRecordsResponse: core.serialization.ObjectSchema<
    serializers.GetAllAccountingRecordsResponse.Raw,
    PropifyApi.GetAllAccountingRecordsResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).AccountingRecord)),
});

export declare namespace GetAllAccountingRecordsResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: (serializers.AccountingRecord.Raw | undefined)[];
    }
}
