/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Resident {
    /** The unique identifier for the resident */
    id: string;
    /** The date record first entered propify */
    createdAt: string;
    /** The date record was last updated in propify */
    updatedAt: string;
    /** The external ID from the source vendor */
    xId: string;
    /** The external lease ID from the source vendor */
    xLeaseId?: string;
    /** First name of the resident */
    firstName?: string;
    /** Middle name of the resident */
    middleName?: string;
    /** Last name of the resident */
    lastName?: string;
    /** Resident date of birth */
    dateOfBirth?: string;
    /** Resident street address line 1 */
    address1?: string;
    /** Resident street address line 2 */
    address2?: string;
    /** Resident city */
    city?: string;
    /** Resident state */
    state?: string;
    /** Resident zip code */
    zip?: string;
    /** Resident phone number */
    phone1?: string;
    /** The type of phone number 1 */
    phone1Type?: string;
    /** Resident phone number 2 */
    phone2?: string;
    /** The type of phone number 2 */
    phone2Type?: string;
    /** Resident email address */
    email1?: string;
    /** Resident email address alternate */
    email2?: string;
    /** Resident street address line 1 alternate */
    address1Alternate?: string;
    /** Resident street address line 2 alternate */
    address2Alternate?: string;
    /** Resident city alternate */
    cityAlternate?: string;
    /** Resident state alternate */
    stateAlternate?: string;
    /** Resident zip code alternate */
    zipAlternate?: string;
    /** Is the resident an employee */
    isEmployee?: boolean;
    /** Notes */
    notes?: string;
    /** The rent balance owed */
    balanceInCents?: number;
    /** The past due rent balance owed */
    lateBalanceInCents?: number;
    /** The property management system of record */
    integrationVendor: string;
}
