/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.listings.getAll.Response.Raw,
    PropifyApi.GetAllListingsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetAllListingsResponse);

export declare namespace Response {
    type Raw = serializers.GetAllListingsResponse.Raw;
}
