/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.workOrders.getAll.Response.Raw,
    PropifyApi.GetAllWorkOrdersResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetAllWorkOrdersResponse);

export declare namespace Response {
    type Raw = serializers.GetAllWorkOrdersResponse.Raw;
}
