/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface Lease {
    /** The unique identifier for the resident */
    id: PropifyApi.ResidentId;
    /** The date record first entered propify */
    createdAt: Date;
    /** The date record was last updated in propify */
    updatedAt: Date;
    /** The external ID from the source vendor */
    xId: string;
    /** The external property ID from the source vendor */
    xPropertyId?: string;
    /** The external resident ID from the source vendor */
    xResidentId?: string;
    /** The external unit ID from the source vendor */
    xUnitId?: string;
    /** The rent amount in cents */
    rentAmountInCents?: number;
    /** The day of the month the rent is due */
    rentDueDay?: number;
    /** The deposit amount in cents */
    depositAmount?: string;
    /** The deposit amount in cents */
    depositAmountAmountInCents?: number;
    /** The date the deposit was received */
    depositDate?: Date;
    /** The date the lease was signed */
    signatureDate?: Date;
    /** The date the lease starts */
    startDate?: Date;
    /** The date the lease ends */
    endDate?: Date;
    /** The date the application was submitted */
    applicationDate?: Date;
    /** The date the resident is scheduled to move in */
    scheduledMoveInDate?: Date;
    /** The date the resident is scheduled to move out */
    scheduledMoveOutDate?: Date;
    /** The date the resident actually moved in */
    realizedMoveInDate?: Date;
    /** The date the resident actually moved out */
    realizedMoveOutDate?: Date;
    /** The status of the lease */
    status?: string;
    /** The type of lease */
    type?: string;
    /** The property management system of record */
    integrationVendor: PropifyApi.IntegrationVendor;
}
