/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface AllApplicants {
    meta: PropifyApi.Meta;
    results: PropifyApi.Applicant[];
}
