/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface Applicant {
    /** The unique identifier for the applicant */
    id: string;
    /** The [date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) record first entered propify */
    createdAt: string;
    /** The [date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) record was last updated in propify */
    updatedAt: string;
    /** The external ID from the source vendor */
    xId: string;
    /** The external lease ID from the source vendor */
    xPropertyId?: string;
    /** First name of the applicant */
    firstName?: string;
    /** Middle name of the applicant */
    middleName?: string;
    /** Last name of the applicant */
    lastName?: string;
    /** Applicant date of birth */
    dateOfBirth?: Date;
    /** Applicant street address line 1 */
    address1?: string;
    /** Applicant street address line 2 */
    address2?: string;
    /** Applicant city */
    city?: string;
    /** Applicant state */
    state?: string;
    /** Applicant zip code */
    zip?: string;
    /** Applicant phone number */
    phone1?: string;
    /** The type of phone number */
    phone1Type?: string;
    /** Applicant alternative phone number */
    phone2?: string;
    /** The type of the alternative phone number */
    phone2Type?: string;
    /** Applicant email address */
    email1?: string;
    /** Applicant email address alternative */
    email2?: string;
    /** Notes about the applicant */
    notes?: string;
    /** The property management system of record */
    integrationVendor: PropifyApi.IntegrationVendor;
}
