/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.properties.getAllProperties.Response.Raw,
    PropifyApi.AllProperties
> = core.serialization.lazyObject(async () => (await import("../../..")).AllProperties);

export declare namespace Response {
    type Raw = serializers.AllProperties.Raw;
}
