/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface AllWorkOrders {
    meta: PropifyApi.Meta;
    results: PropifyApi.WorkOrder[];
}
