/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface AllProperties {
    meta: PropifyApi.Meta;
    results: PropifyApi.Property[];
}
