/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface Property {
    /** The unique identifier for the property */
    id: string;
    /** The date record first entered propify */
    createdAt: Date;
    /** The date record was last updated in propify */
    updatedAt: Date;
    /** The external ID from the source vendor */
    xId: string;
    /** The name of the property */
    name?: string;
    /** The number of units in the property */
    numberOfUnits?: number;
    /** The first line of the street address */
    streetAddress1?: string;
    /** The second line of the street address */
    streetAddress2?: string;
    /** The city */
    city?: string;
    /** The state */
    state?: string;
    /** The zip code */
    zip?: string;
    /** The year the property was built */
    yearBuilt?: number;
    /** The name of the property manager */
    managerName?: string;
    /** The first phone number of the property manager */
    managerPhone1?: string;
    /** The type of the first phone number of the property manager */
    managerPhone1Type?: string;
    /** The second phone number of the property manager */
    managerPhone2?: string;
    /** The type of the second phone number of the property manager */
    managerPhone2Type?: string;
    /** The email address of the property manager */
    managerEmail?: string;
    /** The property management system of record */
    integrationVendor: PropifyApi.IntegrationVendor;
}
