/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PropifyApi } from "@fern-api/propify";

export interface GetAllUnitPricesResponse {
    meta: PropifyApi.Metadata;
    results: (PropifyApi.UnitPrice | undefined)[];
}
