/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const DefaultError: core.serialization.Schema<serializers.DefaultError.Raw, PropifyApi.DefaultErrorType> =
    core.serialization.lazyObject(async () => (await import("../../..")).DefaultErrorType);

export declare namespace DefaultError {
    type Raw = serializers.DefaultErrorType.Raw;
}
