/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllWorkOrders: core.serialization.ObjectSchema<serializers.AllWorkOrders.Raw, PropifyApi.AllWorkOrders> =
    core.serialization.object({
        meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
        results: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).WorkOrder)
        ),
    });

export declare namespace AllWorkOrders {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.WorkOrder.Raw[];
    }
}
