/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllWorkOrdersResponse: core.serialization.ObjectSchema<
    serializers.GetAllWorkOrdersResponse.Raw,
    PropifyApi.GetAllWorkOrdersResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).WorkOrder)),
});

export declare namespace GetAllWorkOrdersResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: serializers.WorkOrder.Raw[];
    }
}
