/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const WorkOrder: core.serialization.ObjectSchema<serializers.WorkOrder.Raw, PropifyApi.WorkOrder> =
    core.serialization.object({
        id: core.serialization.string(),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string()),
        xId: core.serialization.property("x_id", core.serialization.string()),
        xPropertyId: core.serialization.property("x_property_id", core.serialization.string().optional()),
        xUnitId: core.serialization.property("x_unit_id", core.serialization.string().optional()),
        xResidentId: core.serialization.property("x_resident_id", core.serialization.string().optional()),
        details: core.serialization.string().optional(),
        dueDate: core.serialization.property("due_date", core.serialization.string().optional()),
        completedDate: core.serialization.property("completed_date", core.serialization.string().optional()),
        entryContact: core.serialization.property("entry_contact", core.serialization.string().optional()),
        entryDate: core.serialization.property("entry_date", core.serialization.string().optional()),
        entryType: core.serialization.property("entry_type", core.serialization.string().optional()),
        invoiceAmount: core.serialization.property("invoice_amount", core.serialization.number().optional()),
        invoiceNumber: core.serialization.property("invoice_number", core.serialization.string().optional()),
        notes: core.serialization.string().optional(),
        priority: core.serialization.string().optional(),
        status: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
        integrationVendor: core.serialization.property("integration_vendor", core.serialization.string()),
    });

export declare namespace WorkOrder {
    interface Raw {
        id: string;
        created_at: string;
        updated_at: string;
        x_id: string;
        x_property_id?: string | null;
        x_unit_id?: string | null;
        x_resident_id?: string | null;
        details?: string | null;
        due_date?: string | null;
        completed_date?: string | null;
        entry_contact?: string | null;
        entry_date?: string | null;
        entry_type?: string | null;
        invoice_amount?: number | null;
        invoice_number?: string | null;
        notes?: string | null;
        priority?: string | null;
        status?: string | null;
        type?: string | null;
        integration_vendor: string;
    }
}
