/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PropifyApiEnvironment = {
    Demo: "demo.getpropify.com/v1",
} as const;

export type PropifyApiEnvironment = typeof PropifyApiEnvironment.Demo;
