/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PropifyApiEnvironment = {
    Demo: "https://demo.getpropify.com/v1",
    Production: "https://api.getpropify.com/v1",
} as const;

export type PropifyApiEnvironment = typeof PropifyApiEnvironment.Demo | typeof PropifyApiEnvironment.Production;
