/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const AllRentPaymentHistory: core.serialization.ObjectSchema<
    serializers.AllRentPaymentHistory.Raw,
    PropifyApi.AllRentPaymentHistory
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Meta),
    results: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).RentPaymentHistory)
    ),
});

export declare namespace AllRentPaymentHistory {
    interface Raw {
        meta: serializers.Meta.Raw;
        results: serializers.RentPaymentHistory.Raw[];
    }
}
