/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const GetAllRentPaymentRecordsResponse: core.serialization.ObjectSchema<
    serializers.GetAllRentPaymentRecordsResponse.Raw,
    PropifyApi.GetAllRentPaymentRecordsResponse
> = core.serialization.object({
    meta: core.serialization.lazyObject(async () => (await import("../../..")).Metadata),
    results: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).RentPaymentRecord)
    ),
});

export declare namespace GetAllRentPaymentRecordsResponse {
    interface Raw {
        meta: serializers.Metadata.Raw;
        results: serializers.RentPaymentRecord.Raw[];
    }
}
