/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const RentPaymentRecord: core.serialization.ObjectSchema<
    serializers.RentPaymentRecord.Raw,
    PropifyApi.RentPaymentRecord
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.string()),
    xId: core.serialization.property("x_id", core.serialization.string()),
    xLeaseId: core.serialization.property("x_lease_id", core.serialization.string().optional()),
    xResidentId: core.serialization.property("x_resident_id", core.serialization.string().optional()),
    xPropertyId: core.serialization.property("x_property_id", core.serialization.string().optional()),
    amountInCents: core.serialization.property("amount_in_cents", core.serialization.number().optional()),
    dateReceived: core.serialization.property("date_received", core.serialization.string().optional()),
    paymentType: core.serialization.property("payment_type", core.serialization.string().optional()),
    paymentStatus: core.serialization.property("payment_status", core.serialization.string().optional()),
    integrationVendor: core.serialization.property("integration_vendor", core.serialization.string()),
});

export declare namespace RentPaymentRecord {
    interface Raw {
        id: string;
        created_at: string;
        updated_at: string;
        x_id: string;
        x_lease_id?: string | null;
        x_resident_id?: string | null;
        x_property_id?: string | null;
        amount_in_cents?: number | null;
        date_received?: string | null;
        payment_type?: string | null;
        payment_status?: string | null;
        integration_vendor: string;
    }
}
