/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.residents.get.Response.Raw,
    PropifyApi.GetResidentResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).GetResidentResponse);

export declare namespace Response {
    type Raw = serializers.GetResidentResponse.Raw;
}
