/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const ApplicantId: core.serialization.Schema<serializers.ApplicantId.Raw, PropifyApi.ApplicantId> =
    core.serialization.string();

export declare namespace ApplicantId {
    type Raw = string;
}
