/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const DefaultErrorType: core.serialization.ObjectSchema<
    serializers.DefaultErrorType.Raw,
    PropifyApi.DefaultErrorType
> = core.serialization.object({
    error: core.serialization.lazyObject(async () => (await import("../../..")).ErrorMessage),
});

export declare namespace DefaultErrorType {
    interface Raw {
        error: serializers.ErrorMessage.Raw;
    }
}
