/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const IntegrationVendor: core.serialization.Schema<
    serializers.IntegrationVendor.Raw,
    PropifyApi.IntegrationVendor
> = core.serialization.enum_(["DoorLoop", "Buildium", "Yardi"]);

export declare namespace IntegrationVendor {
    type Raw = "DoorLoop" | "Buildium" | "Yardi";
}
