/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PropifyApi } from "@fern-api/propify";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.leases.getAllLeases.Response.Raw, PropifyApi.AllLeases> =
    core.serialization.lazyObject(async () => (await import("../../..")).AllLeases);

export declare namespace Response {
    type Raw = serializers.AllLeases.Raw;
}
